### PR TITLE
ENHANCEMENT added trace logging

### PR DESCRIPTION
**Pull request by nsfyn55**
@tgross / @Ry4an Hey gents here is the PR for the trace logging. Sorry for the delay

related issue Dramafever/www#13489

### CODE REVIEW

**Comment by nsfyn55** [comment]
Fixed.

**Comment by Ry4an** [comment]
LGTM.  Why'd you close the PR?

**Comment by nsfyn55** [comment]
@Ry4an We aren't merging( and this repo doesn't have `Do Not Merge` flag. @tgross is just going to deploy the changes off the branch temporarily on one host, Since we are going to run production requests on it I thought it should go through a PR process.

or at least that was my understanding.

**Comment by tgross** [comment]
Going to deploy this morning.

**Comment by nsfyn55** [comment]
@tgross here was my logging config...

```python
# ------------------------- 
# LOGGING CONFIGURATION 
# ------------------------- 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters':{
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(pathname)s:%(lineno)d %(process)d %(thread)d %(message)s'
            },
        'simple': {
            'format': '%(asctime)s,%(message)s'
            },
        },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            },
        'cache_log_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': 'cache.log'
            },
        },
    'loggers': {
        'django': {
            'handlers':['console'],
            'propagate': True,
            'level':'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            },
        'df_cache_logger': {
            'handlers': ['cache_log_file'],
            'level': 'DEBUG',
            'propagate': False,
            },
        },
    }
```

**Pull request closed without merging**
